CREATE TABLE CUSTOMER(
    CUSTOMER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE PRODUCT(
    PRODUCT_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR(50),
    NAME VARCHAR(100),
    DESCRIPTION VARCHAR(300),
    UNITY_COST NUMERIC(20,20)
);

CREATE TABLE ORDER_INFO(
    ORDER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INTEGER REFERENCES CUSTOMER (CUSTOMER_ID),
    ORDER_DATE TIMESTAMP,
    ORDER_TOTAL_COST NUMERIC(20,2)
);

CREATE TABLE ORDER_PRODUCT(
    ORDER_PRODUCT_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INTEGER REFERENCES ORDER_INFO (ORDER_ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT (PRODUCT_ID),
    QUANTITY NUMERIC(20)
);